apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
    environment: dev
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      environment: dev
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        environment: dev
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          readinessProbe:
            initialDelaySeconds: 5
            #sucessTreshold: 1
            failureThreshold: 5
            periodSeconds: 5
            httpGet:
              path: /
              port: 80
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            #sucessThreshold: 1
            failureThreshold: 35
            exec:
              command:
                - curl
                - http://localhost:80