# Deploy
replicaCount: 4
# Container
image:
  repository: nginx
  tag: latest

# Resources
resources:
  requests:
    memory: 250Mi
    cpu: "0.1"
  limits:
    memory: "800Mi"
    cpu: "0.8"

# ConfigMap
configmap:
  dadossre:
    name: Leopoldo P. Cardoso
    email: leopoldo.cardoso@lpcinfo.com.br

# Readiness
readinessprobe:
  initialDelaySeconds: 5
  successThreshold: 1
  failureThreshold: 5
  periodSeconds: 5

# Liveness
livenessprobe:
  initialDelaySeconds: 5
  successThreshold: 1
  failureThreshold: 5
  periodSeconds: 5

